on:
  push:
    branches:
      - 'feature/**'
      - 'develop'
      - 'hotfix/**'
      - 'release/**'
    tags-ignore:
      - '**'

jobs:
  run-tests:
    name: Run tests only
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test