on:
  push:
    tags:
      - 'v*.*.*'                  # Solo al etiquetar v1.0.0, v2.3.4, etc.
  workflow_dispatch:
jobs:
  usar-receta-compartida:
    uses: BenjaminDuran/AUY1104-BenjaminDuran-Primary/.github/workflows/deployapi.yml@main
    with:
      image-name: demo-api
      image-tag: ${{ github.ref_name }}  # ej. v1.2.3 — misma etiqueta que en Git
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
